import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/components/Navigation/NavBar";
import { barlow } from "./fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${barlow.className} antialiased`}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
